image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3.5.0-jdk-8
  stage: build
  script:
  - cd backend
  - mvn package -B
  artifacts:
    paths:
      - /backend/target/*.war

docker-build:
  stage: package
  script:
  - cd backend
  - docker build -t registry.gitlab.com/aliariff/rabatt/image .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker push registry.gitlab.com/aliariff/rabatt/image

k8s-deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
  - echo "deploying...."
