image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3.5.0-jdk-8
  stage: build
  script:
  - cd backend
  - mvn package -B
  artifacts:
    paths:
      - backend/target/*.war

docker-build:
  stage: package
  script:
  - cd backend
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t latest $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:7} .
  - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA:0:7}

deploy:
  stage: deploy
  script:
  - echo "deploying...."
