image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: registry.gitlab.com/aliariff/rabatt:${CI_COMMIT_SHA:0:8}

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3.5.0-jdk-8
  stage: build
  script:
  - cd backend
  - mvn package -B
  artifacts:
    paths:
      - backend/target/*.war

docker-build:
  stage: package
  script:
  - cd backend
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $CONTAINER_IMAGE
  - docker push $CONTAINER_IMAGE

deploy:
  stage: deploy
  script:
  - echo "deploying...."
