image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy

before_script:
  - export IMAGE_TAG_SHA=${CI_COMMIT_SHA:0:7}

maven-build:
  image: maven:3.5.0-jdk-8
  stage: build
  script:
    - cd backend
    - mvn package -B
  artifacts:
    paths:
      - backend/target/*.war

docker-build:
  stage: package
  script:
    - cd backend
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t $CI_REGISTRY_IMAGE:${IMAGE_TAG_SHA} -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE

deploy:
  image: williamyeh/ansible:debian8
  stage: deploy
  environment:
    name: production
    url: http://kildin.informatik.rwth-aachen.de:1234/rabatt/api/v1/users/
  script:
    - cd backend/deploy
    - ansible-playbook site.yml -v -i production --extra-vars "ansible_ssh_pass=${SSH_PASS}"
