version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testing

  backend:
    depends_on:
      - db
    image: registry.gitlab.com/aliariff/rabatt:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      RABATT_ENV: development
      MYSQL_HOST: jdbc:log4jdbc:mysql://db:3306/rabattdb?createDatabaseIfNotExist=true
      MYSQL_USER: root
      MYSQL_PASSWORD: testing

volumes:
  db_data:
    external: true
